name: capilla_san_juan_bautista
description: "Aplicación de la Capilla San Juan Bautista."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  http: ^1.2.2
  in_app_update: ^4.2.3
  flutter_launcher_icons: ^0.14.4
  loading_animation_widget: ^1.3.0
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/data/
    - assets/grupos/
    - assets/adoracion/
    - assets/capillita/
    - assets/patio/
    - assets/icon.png
    - assets/icon_512x512.png
    - assets/capilla_san_juan_bautista.jpg
    - assets/capilla_san_juan_bautista_old.jpg
    - assets/hijas_de_santa_ana.jpg
    - assets/carmelitas.jpeg
    - assets/chio.jpg
    - assets/mirtha.png
    - assets/hernan.png
